#!/bin/bash

# ------------------------------------------------------------------
#
#  dr-install : docker runner installer
#  manage docker containers in a simple and consistent way.
#  
#  See:
#    https://github.com/j842/dr
#
# ------------------------------------------------------------------


# Global constants.
readonly DRETCDIR="/etc/dr"
readonly DR_CFG_FILE="${DRETCDIR}/dr.cfg"
readonly SUPPORTIMAGE="j842/docker-dr"
readonly DRBINDIR="bin"

#------------------------------------------------------------------------------------


# showusage
function showusage {
cat <<'EOF' >&2

NAME
   dr-install - install the Docker Runner framework
    
SYNOPSIS
   dr-install DIRECTORY

DESCRIPTION
   Docker Runner Provides a standard way to manage and run containers.
   This script installs Docker Runner on a Debian system, with all files
   stored under DIRECTORY.
   
   See https://github.com/j842/dr
   
EXIT CODE
   0   - success
   1   - error
   3   - no changes made
   
EOF
}

#------------------------------------------------------------------------------------

# copydrfiles
function copydrfiles {
   # the directory that the container will update.
   local DRBINPATH="${DIRECTORY}/${DRBINDIR}"
   if [ -d "${DRBINPATH}" ]; then
      rm -r "${DRBINPATH}"
   fi
   mkdir -p "${DRBINPATH}"
   
   # assumes docker image does not use entrypoint. Could instead override entrypoint maybe.
   docker run --rm -it -v "${DRBINPATH}:/tempcopy" "${SUPPORTIMAGE}" /bin/bash -c "cp -a /dr/* /tempcopy/"                             
   if [ $? -ne 0 ]; then 
      echo "Failed to copy files.">&2 
      echo "You will need to reinstall Docker Runner.">&2
      rm -r "${DIRECTORY}" "${DRETCDIR}"
      exit 1
   fi  
   chown -R root:root "${DRBINPATH}"
   chmod -R a-w "${DRBINPATH}"
}

#------------------------------------------------------------------------------------

# configure
function configure {
   if [ -z $1 ]; then echo "dr-install requires directory argument.">&2 ; exit 1 ; fi
   DIRECTORY="$1"
   mkdir -p "$DRETCDIR"   # ensure directrory exists.   
   DATESTAMP="$(LC_ALL=C date -u +"%a, %d %b %Y %X %z")"

cat <<EOF >"${DR_CFG_FILE}"
# Docker Runner configuration file.
# Last modified ${DATESTAMP}

DIRECTORY=${DIRECTORY}
EOF
   
   # creates DIRECTORY and populates the bin folder from SUPPORTIMAGE.
   copydrfiles
   
   # set up standard docker user and group for containers.
   # groupadd -g 22022 "$DRGROUP"
   # adduser --disabled-password --gecos '' -u 22022 --gid 22022 "$DRUSER"
   
   echo "Configuration complete, Docker Runner is ready to use! Try running  dr  now." >&2
}

#------------------------------------------------------------------------------------


# MAIN

if [ "$EUID" -ne 0 ]; then echo "Please run as root" ; exit 1 ; fi

if ! command_exists docker ; then
   echo "Please install Docker before using Docker Runner.">&2
   echo "(e.g. use  https://github.com/j842/scripts/blob/master/install_docker.sh )">&2
   exit 1
fi
if [ "$(uname -rv | grep -c Debian)" -eq 0 ]; then
   echo "This script is currently only for Debian hosts.">&2
   exit 1
fi
# Check basic commands are available
COMMANDS=(gpg wget md5sum 7z 7za)
for NEEDEDCMD in "${COMMANDS[@]}"; do
  if ! command_exists "${NEEDEDCMD}" ; then 
      echo "Docker Runner requires ${NEEDEDCMD} to be available for scripts." >&2 
      echo "After Docker is installed, install all other dependencies with: ">&2 
      echo " ">&2
      echo "apt-get install -y gnupg p7zip-full">&2 
      echo " ">&2
      exit 1 
  fi
done

if [ "$1" ]; then
   configure "$1"
else
   showusage
   exit 1
fi
   



