#!/bin/bash
set -o errexit
set -o nounset

#
# ██████╗ ██████╗ ██╗   ██╗███╗   ██╗███╗   ██╗███████╗██████╗       ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     
# ██╔══██╗██╔══██╗██║   ██║████╗  ██║████╗  ██║██╔════╝██╔══██╗      ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     
# ██║  ██║██████╔╝██║   ██║██╔██╗ ██║██╔██╗ ██║█████╗  ██████╔╝█████╗██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     
# ██║  ██║██╔══██╗██║   ██║██║╚██╗██║██║╚██╗██║██╔══╝  ██╔══██╗╚════╝██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     
# ██████╔╝██║  ██║╚██████╔╝██║ ╚████║██║ ╚████║███████╗██║  ██║      ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗
# ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝      ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝
#                                                                                                                          
#                                                                            
#
#  dRunner installer
#  Manage docker containers in a simple and consistent way.
#  
#  See:
#    https://github.com/j842/drunner
#
# ------------------------------------------------------------------
readonly CODE_S="\e[32m"
readonly CODE_E="\e[0m"
#------------------------------------------------------------------------------------

# command_exists
function command_exists { command -v "$1" >/dev/null 2>&1 ; }

#------------------------------------------------------------------------------------

# die MESSAGE 
function die {
   if [ "$#" -eq 1 ]; then
      echo "$1" <&2
   else
      echo "Unexpected error. Exiting."<&2
   fi
   exit 1
}

#------------------------------------------------------------------------------------

# showusage
function showusage {
cat <<'EOF' >&2

NAME
   drunner-install - install the dRunner framework
    
SYNOPSIS
   drunner-install [ROOTPATH]

DESCRIPTION
   dRunner Provides a standard way to manage and run containers.
   This script installs dRunner on a Debian system, with all files
   stored under ROOTPATH, which defaults to /opt/drunner.
      
   See https://github.com/j842/drunner
   
EXIT CODE
   0   - success
   1   - error
   3   - no changes made
   
EOF
}

#------------------------------------------------------------------------------------

# copydrfiles
function copydrfiles {
   if [ -d "${ROOTPATH}/support" ]; then
      rm -r "${ROOTPATH}/support"
   fi
   mkdir -p "${ROOTPATH}/support"
   
   if [ ! -d "${ROOTPATH}/services" ]; then
      mkdir -p "${ROOTPATH}/services"
   fi
    
   docker run --rm -it -v "${ROOTPATH}/support:/tempcopy" "${SUPPORTIMAGE}" /bin/bash -c "cp -r /support/* /tempcopy/"                             
   if [ $? -ne 0 ]; then 
      echo "Failed to copy files.">&2 
      echo "You will need to reinstall dRunner.">&2
      rm -r "${ROOTPATH}" "/etc/drunner"
      exit 1
   fi  
   # set ownership and permissions.
   chown -R root:root "${ROOTPATH}/support"
   chmod -R 0500 "${ROOTPATH}/support"
   chmod -R 0555 "${ROOTPATH}/support/run_on_service"

   local DREXEC="/usr/local/bin/drunner"
   if [ -e "$DREXEC" ]; then rm "$DREXEC" ; fi
   ln -s "${ROOTPATH}/support/drunner" "$DREXEC"
}

#------------------------------------------------------------------------------------

# configure
function configure {   
   UPDATE=""
   if [ -e "${ROOTPATH}/support/buildtime.sh" ]; then
      source "${ROOTPATH}/support/buildtime.sh"
      UPDATE="${SUPPORTBUILDTIME}"
   fi
   
   mkdir -p "/etc/drunner"   # ensure directrory exists.   
   local DATESTAMP="$(TZ=Pacific/Auckland date)"

   # ensure we have the latest support image.
   if [ "$PULLONUPDATE" -eq 1 ]; then
      docker pull "${SUPPORTIMAGE}"
      if [ "$?" -ne 0 ]; then die "Unable to pull required Docker image ${SUPPORTIMAGE}." ; fi
   fi

cat <<EOF >"/etc/drunner/config.sh"
# Docker Runner configuration file.
# You can edit this file - user changes are preserved on update.
# Last generated ${DATESTAMP}

readonly ROOTPATH="${ROOTPATH}"
readonly SUPPORTIMAGE="${SUPPORTIMAGE}"
readonly PULLONUPDATE=${PULLONUPDATE}
readonly DRUNNERINSTALLURL="${DRUNNERINSTALLURL}"
readonly DRUNNERINSTALLTIME="${DATESTAMP}"
EOF
   
   # creates ROOTPATH and populates the bin folder from SUPPORTIMAGE.
   copydrfiles
   
   source "${ROOTPATH}/support/buildtime.sh"
         
   if [ -n "$UPDATE" ]; then
      echo " ">&2
      echo "Updated with ${SUPPORTIMAGE}">&2
      echo " ">&2
      echo "Previous Support Build: ${UPDATE}">&2
      echo "New Support Build:      ${SUPPORTBUILDTIME}">&2
      echo " ">&2
      echo -e "Update complete. Try running ${CODE_S}drunner${CODE_E} now." >&2
      echo " ">&2      
   else
      echo " ">&2
      echo " ">&2
      echo -e "Installation complete! Try running ${CODE_S}drunner${CODE_E} now." >&2
      echo " ">&2
   fi
}

#------------------------------------------------------------------------------------

# MAIN

if [ "$EUID" -ne 0 ]; then echo "Please run as root" ; exit 1 ; fi

if ! command_exists docker ; then
   echo "Please install Docker before using dRunner.">&2
   echo "(e.g. use  https://raw.githubusercontent.com/j842/scripts/master/install_docker.sh )">&2
   exit 1
fi
if [ "$(uname -rv | grep -c Debian)" -eq 0 ]; then
   die "This script is currently only for Debian hosts."
fi

if [ "$#" -gt 1 ]; then
   showusage
   exit 1  
fi

ROOTPATH="/opt/drunner"
PULLONUPDATE=1
SUPPORTIMAGE="drunner/support:latest"
DRUNNERINSTALLURL="https://raw.githubusercontent.com/j842/dRunner/master/drunner-install"

# preserve existing settings if present.
[ ! -e "/etc/drunner/config.sh" ] || source "/etc/drunner/config.sh"

# if caller specified ROOTPATH then override with that.
[ $# -eq 0 ] || ROOTPATH="$1"

configure
