#!/bin/bash
set -o nounset

# ██████╗ ███████╗ ██████╗ ██████╗ ███╗   ███╗██████╗ ██████╗ ███████╗███████╗███████╗
# ██╔══██╗██╔════╝██╔════╝██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝
# ██║  ██║█████╗  ██║     ██║   ██║██╔████╔██║██████╔╝██████╔╝█████╗  ███████╗███████╗
# ██║  ██║██╔══╝  ██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██╔══██╗██╔══╝  ╚════██║╚════██║
# ██████╔╝███████╗╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ██║  ██║███████╗███████║███████║
# ╚═════╝ ╚══════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝


readonly MYDIR=$( dirname "$(readlink -f "$0")" )
ROOTPATH=$(realpath "$MYDIR/../" | tr -d '\r\n')
source "${ROOTPATH}/support/drunner-util-functions.sh"

#------------------------------------------------------------------------------------
# PASS=? decompress DESTPATH/VOLUME ARCHIVEFOLDER ARCHIVENAME

if [ $# -ne 3 ]; then die "PASS=? decompress DESTPATH/VOLUME ARCHIVEFOLDER ARCHIVENAME" ; fi

if [ -d "$1" ]; then
   # path
   DEST=$(realpath "$1" | tr -d '\r\n')
   if [ $? -ne 0 ]; then die "decompress: Couldn't find destination path ${1}." ; fi
else
   # volume
   volexists "$1"
   if [ $? -ne 0 ]; then die "$1 is not a valid path nor Docker volume container." ; fi
   DEST="$1"
fi

ARCHIVEFOLDER=$(realpath "$2" | tr -d '\r\n')
if [ $? -ne 0 ]; then die "decompress: Couldn't find source path ${2}." ; fi

ARCHIVENAME="$3"

if [ ! -e "${ARCHIVEFOLDER}/${ARCHIVENAME}" ]; then
   die "decompress: archive does not exist: ${ARCHIVEFOLDER}/${ARCHIVENAME}";
fi

# ensure PASS exists.
[ -v PASS ] || PASS=""

docker run -i -t --name="dr_decompress" -e "PASS=${PASS}" \
            -v "${ARCHIVEFOLDER}:/src" -v "${DEST}:/dst" \
            drunner/install-rootutils dr_decompress "${ARCHIVENAME}"
RVAL=$?
docker rm "dr_decompress" >/dev/null 2>&1

exit "$RVAL"
